// Searcher module: Executes queries against the inverted index
// Handles query parsing and result retrieval

const Tokenizer = require('../indexer/tokenizer');
const InvertedIndex = require('../indexer/inverted-index');
const Ranker = require('./ranker');

class Searcher {
  constructor(indexer) {
    this.indexer = indexer;
    this.tokenizer = new Tokenizer();
    this.ranker = new Ranker();
    this.ranker.setIndexer(indexer);
  }

  /**
   * Search for a query and return ranked results
   */
  search(query, options = {}) {
    const {
      limit = 10,
      offset = 0,
      includeMetadata = true
    } = options;

    // Parse query
    const tokens = this.tokenizer.process(query);

    if (tokens.length === 0) {
      return {
        results: [],
        total: 0,
        query: query,
        tokens: []
      };
    }

    // Get results from index
    const indexResults = this.indexer.index.searchMultiple(tokens);

    // Build results with document metadata
    const results = this.buildResults(indexResults, includeMetadata);

    // Rank results
    const rankedResults = this.ranker.rank(results, query, tokens);

    // Apply pagination
    const paginatedResults = rankedResults.slice(offset, offset + limit);

    return {
      results: paginatedResults,
      total: results.length,
      query: query,
      tokens: tokens,
      page: Math.floor(offset / limit) + 1,
      limit: limit
    };
  }

  /**
   * Build results with document metadata
   */
  buildResults(indexResults, includeMetadata = true) {
    return indexResults.map(result => {
      const document = this.indexer.getDocument(result.documentId);

      return {
        url: result.documentId,
        score: result.score,
        title: document?.title || 'Untitled',
        description: document?.description || '',
        snippet: '', // Will be generated by ranker
        crawlTime: document?.crawlTime
      };
    });
  }

  /**
   * Search for an exact phrase (all tokens must appear in sequence)
   */
  searchPhrase(query, options = {}) {
    const { limit = 10 } = options;

    const tokens = this.tokenizer.processWithPositions(query);

    if (tokens.length === 0) {
      return [];
    }

    // Get posting list for first term
    const firstTerm = tokens[0].token;
    const firstPostings = this.indexer.index.getPostingList(firstTerm);

    if (!firstPostings) {
      return [];
    }

    const results = [];

    // For each document containing the first term
    for (const documentId of firstPostings.documents) {
      const positions = firstPostings.positions.get(documentId);
      const document = this.indexer.getDocument(documentId);

      // Check if all terms appear in sequence
      let matchFound = false;

      for (const startPos of positions) {
        let allMatch = true;

        for (let i = 1; i < tokens.length; i++) {
          const term = tokens[i].token;
          const termPostings = this.indexer.index.getPostingList(term);

          if (!termPostings || !termPostings.positions.has(documentId)) {
            allMatch = false;
            break;
          }

          const termPositions = termPostings.positions.get(documentId);
          const expectedPos = startPos + tokens[i].position - tokens[0].position;

          if (!termPositions.includes(expectedPos)) {
            allMatch = false;
            break;
          }
        }

        if (allMatch) {
          matchFound = true;
          break;
        }
      }

      if (matchFound) {
        results.push({
          url: documentId,
          title: document?.title || 'Untitled',
          description: document?.description || '',
          score: 1.0, // Phrase match gets max relevance
          phraseMatch: true
        });
      }
    }

    return results.slice(0, limit);
  }

  /**
   * Get search suggestions based on prefix
   */
  getSuggestions(prefix, limit = 5) {
    const terms = this.indexer.index.getTerms();
    const normalizedPrefix = prefix.toLowerCase();

    return terms
      .filter(term => term.startsWith(normalizedPrefix))
      .sort((a, b) => {
        // Sort by frequency (more common first)
        const freqA = this.indexer.index.getDocumentCount(a);
        const freqB = this.indexer.index.getDocumentCount(b);
        return freqB - freqA;
      })
      .slice(0, limit);
  }

  /**
   * Get related terms for a query
   */
  getRelatedTerms(query, limit = 5) {
    const tokens = this.tokenizer.process(query);
    const relatedTerms = new Set();

    for (const token of tokens) {
      const postingList = this.indexer.index.getPostingList(token);

      if (postingList) {
        // Get terms that frequently co-occur with this term
        for (const documentId of postingList.documents) {
          // This is a simplified implementation
          // In a real search engine, you'd track co-occurrence more carefully
        }
      }
    }

    return Array.from(relatedTerms).slice(0, limit);
  }
}

module.exports = Searcher;